<?php

namespace AppBundle\Repository;

/**
 * AnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuncioRepository extends \Doctrine\ORM\EntityRepository
{
}
