anuncio_index:
    path:     /
    defaults: { _controller: "AppBundle:Anuncio:index" }
    methods:  GET


anuncio_list:
    path:     /{category}/list
    defaults: { _controller: "AppBundle:Anuncio:list" }
    methods:  GET




anuncio_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Anuncio:show" }
    methods:  GET

anuncio_new:
    path:     /new
    defaults: { _controller: "AppBundle:Anuncio:new" }
    methods:  [GET, POST]

anuncio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Anuncio:edit" }
    methods:  [GET, POST]

anuncio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Anuncio:delete" }
    methods:  DELETE
